#!/usr/bin/env php
<?php



use App\Resources\Common\Utilities\ConfigManager;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;



require __DIR__ . '/../src/Setup/paths.php';
require SOURCE_PATH . '/bootstrap.php';



$container = require SETUP_PATH . '/container.php';
$entityManager = $container->get(EntityManager::class);
$config = $container->get(ConfigManager::class);

// [CAUTION] This operation should not be executed in a production environment!
if ($config->get('is.prod'))
  exit(1);

ConsoleRunner::run(
  new SingleManagerProvider($entityManager)
);
