#!/usr/bin/env php
<?php



use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;



require __DIR__ . '/../src/Setup/paths.php';
require SOURCE_PATH . '/bootstrap.php';



$container = require SETUP_PATH . '/container.php';
$entityManager = $container->get(EntityManager::class);

ConsoleRunner::run(
  new SingleManagerProvider($entityManager)
);
