#!/usr/bin/env sh



# exit if error happens
set -e



# go to docker
script_dir="$(dirname "$0")"
cd "$script_dir"
cd "../docker"




# compose
docker-compose \
  --env-file ../.env \
  --project-name mojeklima \
  up \
  --detach \
  --build



# wait for containers to be initialized
sleep 5



# post-script
docker exec mojeklima-api php ./cli/doctrine orm:schema-tool:create
