#!/usr/bin/env sh



# exit if error happens
set -e



# go to docker
script_dir="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$script_dir"
cd "../docker"



# load environment
. ../.env



# before up

if [ "$APP_MODE" = "production" ]
then
	# group, permission
	# 82 corresponds with ID of a www-data group in php fpm alpine container
	chown :82 ../storage
	chown :82 ../storage/compilation
	chmod g+rw ../storage
	chmod g+rw ../storage/compilation
fi

# remove compiled container
find ../storage/compilation/ -type f -not -name '.gitignore' -exec rm {} \;

# prepare arguments
arguments=""

if [ "$APP_MODE" = "production" ]
then
	arguments="--no-dev --optimize-autoloader"
fi

# install dependencies
docker run --rm --interactive --tty --volume "$PWD/../:/app" composer install --no-ansi  --no-interaction --no-plugins --no-progress --no-scripts --ignore-platform-reqs $arguments



# compose
docker-compose \
  --env-file ../.env \
  --project-name mojeklima \
  up \
  --detach \
  --build
