#!/usr/bin/env sh



# exit if error happens
set -e

# go to docker
script_dir="$(dirname "$0")"
cd "$script_dir"
cd "../docker"

# compose
docker-compose \
  --env-file ../.env \
  --project-name mojeklima \
  up \
  --detach \
  --build

# post
sleep 5

## try to create db schema if not exists yet
docker exec mojeklima-api php ./cli/doctrine orm:schema-tool:create
