#!/usr/bin/env sh



# notice
echo "Notice: This script should be only executed by the /cli/up command in order to work properly"



# prepare env arguments
echo "Waiting 5 seconds for the containers to be initialized..."
sleep 5

docker exec mojeklima-api php ../cli/doctrine orm:schema-tool:create
