#!/usr/bin/env sh



# exit if error happens
set -e



# go to project root
script_dir="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$script_dir"
cd "../"



# load environment
. ./.env



# prepare env arguments
args=""
if [ "$APP_MODE" = "production" ]
then
	args="--no-dev --optimize-autoloader"
fi




# install dependencies
docker run --rm --interactive --tty --volume "$PWD:/app" composer install --no-ansi  --no-interaction --no-plugins --no-progress --no-scripts --ignore-platform-reqs $args
