#!/usr/bin/env sh



# notice
echo "Notice: In order to make script /cli/up-before work properly, please make sure it is only executed only executed by the /cli/up command in order to work properly"



# prepare env arguments
args=""

if [ "$APP_MODE" = "production" ]
then
	args="--no-dev --optimize-autoloader"
fi




# install dependencies
docker run --rm --interactive --tty --volume "$PWD/../:/app" composer install --no-ansi  --no-interaction --no-plugins --no-progress --no-scripts --ignore-platform-reqs $args
