version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mojeklima-api
    restart: always
    working_dir: /var/www/
    networks:
      - network1
    volumes:
      - ../:/var/www
      - ./php:/usr/local/etc/php/conf.d/

  nginx:
    image: nginx:1.25.3-alpine
    container_name: mojeklima-nginx
    networks:
      - network1
    restart: always
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.2
    container_name: mojeklima-db
    restart: always
    networks:
      - network1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../storage/mysql:/var/lib/mysql

  redis:
    image: redis:7.2.3-alpine
    container_name: mojeklima-redis
    restart: always
    networks:
      - network1
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  network1:
    external: true
