version: '3.3'

services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: mojeklima-api
    restart: always
    working_dir: /var/www/
    networks:
      - network1
    volumes:
      - ../:/var/www
      - ./php:/usr/local/etc/php/conf.d/

  nginx:
    image: nginx:1.25.3-alpine
    container_name: mojeklima-nginx
    networks:
      - network1
    restart: always
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.2
    container_name: mojeklima-db
    restart: always
    networks:
      - network1
    environment:
      MYSQL_ROOT_PASSWORD: OFpt5r1RWWZLKYhJB8b9SpNeQcutQye7sl0cuNXIq3CsIlHpbW
      MYSQL_DATABASE: mojeklima
      MYSQL_USER: mojeklima
      MYSQL_PASSWORD: 4N2bZRBLjeH4ff7
    volumes:
      - ../storage/mysql:/var/lib/mysql

  redis:
    image: redis:7.2.3-alpine
    container_name: mojeklima-redis
    restart: always
    networks:
      - network1
    command: redis-server --requirepass NtTUvQKyPURbD7D3p5A2vqdLKPkDyA2UBAT9qdPA32KxqiMbLD

networks:
  network1:
    external: true
